name: mygisapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - gdal
  - fastapi
  - uvicorn
  - pydantic
  - pytest
  - rasterio
  - pysheds
  - numpy=1.25.2
  - matplotlib
  - seaborn
  - geopandas
  - shapely